const lunchIcon = require('../assets/images/lunchIcon.png');
const appIcon = require("../assets/images/appIcon.png");
const Group1 = require("../assets/images/Group1.png");
const Group2 = require("../assets/images/Group2.png");
const Group3 = require("../assets/images/Group3.png");
const fb = require("../assets/images/fb.png");
const google = require("../assets/images/google.png");
const right = require("../assets/images/right.png");
const user = require("../assets/images/user.png");
const king = require("../assets/images/king.png");
const event = require("../assets/images/Event.png");
const event1 = require("../assets/images/Event1.png");
const event2 = require("../assets/images/Event2.png");
const event3 = require("../assets/images/Event3.png");
const event4 = require("../assets/images/Event4.png");
const event5 = require("../assets/images/Event5.png");
const event6 = require("../assets/images/Event6.png");
const event7 = require("../assets/images/Event7.png");
const event8 = require("../assets/images/Event8.png");
const Organizer = require("../assets/images/Organizer.png");
const clander = require("../assets/images/Clander.png");
const invite = require("../assets/images/Invite.png");

export default { lunchIcon,appIcon,Group1,Group2,Group3,fb,google,right,user,king,event,event1,event2,event3,event4,event5,event6,event7,event8,Organizer,clander,invite };